language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ahaf82//react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahaf82/react-test npm test

after_success:
  - docker build -t ahaf82/mulit-client ./client
  - docker build -t ahaf82/mulit-nginx ./nginx
  - docker build -t ahaf82/mulit-server ./server
  - docker build -t ahaf82/mulit-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin 
  # Take those images and push them to docker-hub
  - docker push ahaf82/multi-client
  - docker push ahaf82/multi-nginx
  - docker push ahaf82/multi-server
  - docker push ahaf82/multi-worker
